name: Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Check (clippy)
        run: cargo clippy
      - name: Build
        run: cargo build --release
      - name: Copy shaders and textures
        run: |
          cp -r shaders target/release
          mkdir target/release/textures
          cp textures/board.bmp target/release/textures
          cp textures/pieces.bmp target/release/textures
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: koala_chess_windows
          path: |
            target/release/koala_chess.exe
            target/release/shaders
            target/release/textures
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenGL libraries
        run: sudo apt-get install freeglut3-dev
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Check (clippy)
        run: cargo clippy
      - name: Build
        run: cargo build --release
      - name: Copy shaders and textures
        run: |
          cp -r shaders target/release/shaders
          cp --parents textures/board.bmp target/release
          cp --parents textures/pieces.bmp target/release
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: koala_chess_linux
          path: |
            target/release/koala_chess
            target/release/shaders
            target/release/textures
