name: Rust
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install OpenGL libraries
      run: sudo apt-get install freeglut3-dev
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy
    - name: Check (clippy)
      run: cargo clippy
    - name: Build
      run: cargo build --release
    - name: Upload build artifact
      uses: actions/upload-artifact@2
      with:
        name: koala_chess
        path: target
